Dont send notification if notification type is off in setting
Giveth/notification-center pull request #10
Opened 2022-11-07 07:57 UTC by mohammadranjbarz

related to https://github.com/Giveth/giveth-dapps-v2/issues/709

2022-11-09 16:04 UTC, CarlosQ96 requested changes
Thanks Mohammad I think just add the error and we can merge.

2022-11-09 16:47 UTC, CarlosQ96 commented on src/controllers/v1/notificationsController.ts
> +        //TODO I dont know what should we do in this case
We can log the error to sentry or our logs and not interrupt the process better.

2022-11-10 06:37 UTC, mohammadranjbarz commented on src/controllers/v1/notificationsController.ts
> +        //TODO I dont know what should we do in this case
I dont know what happens if we add a notification type, and user is already in DB, I think about edge cases, so I don't throw exception just add some log to can see if it happend

2022-11-10 06:37 UTC, mohammadranjbarz commented on src/controllers/v1/notificationsController.ts
> +          delete segmentData['email'];
Yeah, let hope it works :))
We should test it to see whether works or not

2022-11-10 06:51 UTC, merged